package common;

public enum TCPMessageType {
	
	LOGIN_REQUEST, 
	REGISTER_REQUEST, 
	CREATE_PROJECT_REQUEST, 
	CHECK_BALANCE_REQUEST, 
	MY_PROJECTS_REQUEST, 
	PROJECT_LEVELS_REQUEST, 
	CHANGE_LEVEL_GOAL_REQUEST
}
