package common;

public enum TCPMessageType {
	
	LOGIN_REQUEST, 
	REGISTER_REQUEST, 
	CREATE_PROJECT_REQUEST, 
	CHECK_BALANCE_REQUEST, 
	MY_PROJECTS_REQUEST, 
	PROJECT_LEVELS_REQUEST, 
	CHANGE_LEVEL_GOAL_REQUEST, 
	ADD_LEVEL_REQUEST, 
	ADD_REWARD_REQUEST, 
	LEVEL_REWARDS_REQUEST, 
	REMOVE_REWARD_REQUEST, 
	REMOVE_LEVEL_REQUEST, 
	ADD_ADMIN_REQUEST
}
